# Generated by Django 3.0.6 on 2020-05-26 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Por comprar', 'Por comprar'), ('Comprando', 'Comprando'), ('Comprado', 'Comprado')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('store', models.CharField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('aditional_info', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Por comprar', 'Por comprar'), ('Comprando', 'Comprando'), ('Comprado', 'Comprado')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('item', models.ManyToManyField(to='listapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('lista', models.ManyToManyField(to='listapp.Lista')),
                ('miembro', models.ManyToManyField(to='listapp.Customer')),
            ],
        ),
    ]
