# Generated by Django 3.0.6 on 2020-05-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='aditional_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Por comprar', 'Por comprar'), ('Comprando', 'Comprando'), ('Comprado', 'Comprado')], max_length=200, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('miembro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listapp.Customer')),
            ],
        ),
    ]
