# Generated by Django 3.0.6 on 2020-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0004_familia_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
