# Generated by Django 3.0.6 on 2020-05-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0005_lista_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='item',
        ),
        migrations.AddField(
            model_name='lista',
            name='item',
            field=models.ManyToManyField(to='listapp.Customer'),
        ),
    ]
