# Generated by Django 3.0.6 on 2020-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0006_auto_20200523_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='item',
            field=models.ManyToManyField(to='listapp.Item'),
        ),
    ]
