# Generated by Django 3.0.6 on 2020-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0007_auto_20200523_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Por comprar', 'Por comprar'), ('Comprando', 'Comprando'), ('Comprado', 'Comprado')], max_length=200, null=True),
        ),
    ]
