# Generated by Django 3.0.6 on 2020-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0009_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='lista',
        ),
        migrations.AddField(
            model_name='familia',
            name='lista',
            field=models.ManyToManyField(to='listapp.Lista'),
        ),
    ]
